---
abstract: 'Catmandu module for working with SRU data'
author:
  - 'Wouter Willaert <wouterw@inuits.eu>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-SRU
provides:
  Catmandu::Importer::SRU:
    file: lib/Catmandu/Importer/SRU.pm
  Catmandu::Importer::SRU::Parser:
    file: lib/Catmandu/Importer/SRU/Parser.pm
  Catmandu::Importer::SRU::Parser::marcxml:
    file: lib/Catmandu/Importer/SRU/Parser/marcxml.pm
  Catmandu::Importer::SRU::Parser::raw:
    file: lib/Catmandu/Importer/SRU/Parser/raw.pm
  Catmandu::Importer::SRU::Parser::simple:
    file: lib/Catmandu/Importer/SRU/Parser/simple.pm
  Catmandu::Importer::SRU::Parser::struct:
    file: lib/Catmandu/Importer/SRU/Parser/struct.pm
  Catmandu::SRU:
    file: lib/Catmandu/SRU.pm
    version: 0.033
requires:
  Catmandu: 0.0302
  Furl: 0.41
  Moo: 1.000003
  URI::Escape: 1.60
  XML::LibXML::Simple: 0.91
  XML::Struct: 0.16
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-SRU/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/LibreCat/Catmandu-SRU
version: 0.033
